#!/usr/bin/env php
<?php

use lord\cos\debug;
use Illuminate\Support\Facades\Artisan;

define('LARAVEL_START', microtime(true));

require __DIR__.'/../vendor/autoload.php';
require __DIR__.'/plg/bot/hlp.php';

$app = new \Illuminate\Foundation\Application(
    dirname(__DIR__)."/src"
);

$app->singleton(
    \Illuminate\Contracts\Console\Kernel::class,
    \lord\cos\kernel::class
);

$app->singleton(
    \Illuminate\Contracts\Debug\ExceptionHandler::class,
    debug::class
);

$kernel = $app->make(\Illuminate\Contracts\Console\Kernel::class);

$kernel->registerCommand(
    app()->make(\Illuminate\Foundation\Console\UpCommand::class)
);

app()->instance("config", new \Illuminate\Config\Repository());

config()->set("database", [
    "driver" => "mysql",
    "host" => "localhost",
    "database" => "paranopg_ghs",
    "username" => "paranopg_ghs",
    "password" => "+I&iVj46(vM9",
    "charset" => "utf8mb4",
    "collation" => "utf8mb4_unicode_ci",
    "prefix" => "",
    "engine" => "InnoDB",
]);

config()->set("queue", [
    'driver' => 'database',
    'table' => 'jobs',
    'queue' => 'default',
    'retry_after' => 90,
    'after_commit' => false,
    'default' => 'database',
    'timeout' => 180
]);

app()->register(\Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class);
app()->register(\Illuminate\Queue\QueueServiceProvider::class);
app()->register(\Illuminate\Cache\CacheServiceProvider::class);
app()->register(\Illuminate\Database\DatabaseServiceProvider::class);

app()->register(\Illuminate\Bus\BusServiceProvider::class);

$kernel->registerCommand($app->make("command.queue.work"));

$kernel->registerCommand($app->make("command.queue.listen"));

$status = $kernel->handle(
    $input = new \Symfony\Component\Console\Input\ArgvInput,
    new \Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);